### ISSUE TITLE
theming issue

### ISSUE THREAD

**Issue by amilz** [g-loot/react-tournament-brackets#18]
not sure if it's my css i'm using otherwise, but unable to get any of the themes to render any different view. 
using x=createTheme, theme={x}. getting no type errors. just no difference in rendering.

**Comment by amilz** [comment]
related. my out of the box theme does not match yours: https://raw.githubusercontent.com/g-loot/react-tournament-brackets/master/images/screenshot_single.png

in case this is helpful, here's what i see. 
![image](https://user-images.githubusercontent.com/85324096/156021399-56bfeaa2-f1f1-4e74-8e1c-dc5ef5d22044.png)

**Comment by Shenato** [comment]
I'll try to answer both issues:
1. That's odd, it worked for me fine, could you provide a sample project or code example so i can re-create it?


2. I don't see much difference in your screenshot other than your background being white, the background is up to you to customize not for me to dictate what it should be via the library 😅 

The library is built with customization in mind, therefore I didn't enforce very specific styling, however I did add a note to the readme recently mentioning that I use https://jgthms.com/minireset.css/ for resetting the browser's default CSS, which probably contributes to why the library looks the way it does for me, also the background color you can change yourself.

I'm open to suggestions but I figured this way would be best since I'm sure most people using this library would want to customize it to look how they want, and I didn't want to have them jump through lots of hoops to override the look and feel of the component.

**Comment by amilz** [comment]
thanks for prompt reply. i'm going to play around a bit. will close the issue and reopen if not able to get it working. thx 🤝
