### ISSUE TITLE
Feature: Ability to show participant picture before his name

### ISSUE THREAD

**Issue by MahmoudTarekAli** [g-loot/react-tournament-brackets#44]

**Comment by Shenato** [comment]
Hey thank you for opening this ticket!

In [this section of the documentation](https://github.com/g-loot/react-tournament-brackets#if-themes-arent-enough-for-you-you-can-always-supply-your-own-match-view-component-and-use-the-props-passed-to-it-to-override-the-match-view-rendering-again-youll-need-to-style-the-round-headers-and-connector-lines-using-options-prop) is an example on how to construct your own Match component with which you can shape the match cell component however you want, and that way you have total freedom to display pictures next to the players.

Let me know if you have any other questions, I will be closing this ticket for now since I don't think the basic API surface level of the component should cater to every single possible need out there when you can make your own match component.
